id: 6
metastore_engine: s3
storage_engine: s3
execution_engine: dask
clients:
  s3:
    configuration:
      access_key: "{{AWS_ACCESS_KEY_ID}}"
      secret_key: "{{AWS_SECRET_ACCESS_KEY}}"
      aws_region: "{{AWS_REGION}}"
  dask:
    configuration:
      runner:
        type: "kubernetes_worker"
        scheduler: "{{DASK_SCHEDULER}}"


      
