id: "2"
type: config
storage_clients:
  - s3
scheduler_clients:
  - glue
metastore_clients:
  - glue
execution_clients:
  - local
clients:
  glue:
    configuration:
      aws_region: "{{AWS_REGION}}"
      aws_role_arn: "{{AWS_ROLE_ARN}}"
      access_key: "{{AWS_ACCESS_KEY_ID}}"
      secret_key: "{{AWS_SECRET_ACCESS_KEY}}"
  local:
    configuration: {}
  s3:
    configuration:
      aws_region: "{{AWS_REGION}}"
      access_key: "{{AWS_ACCESS_KEY_ID}}"
      secret_key: "{{AWS_SECRET_ACCESS_KEY}}"
