id: "4"
type: "config"
metastore_clients: 
  - s3
storage_clients: 
  - s3
execution_clients: 
  - dask
clients:
  s3:
    configuration:
      aws_region: "{{AWS_REGION}}"
      access_key: "{{AWS_ACCESS_KEY_ID}}"
      secret_key: "{{AWS_SECRET_ACCESS_KEY}}"
  dask:
    configuration:
      runner:
        type: "kubernetes_worker"
        scheduler: "{{DASK_SCHEDULER}}"
        
