id: "5"
metastore_clients: s3
storage_clients: s3
execution_clients: local
clients:
  s3:
    configuration:
      aws_region: "{{AWS_REGION}}"
      access_key: "{{AWS_ACCESS_KEY_ID}}"
      secret_key: "{{AWS_SECRET_ACCESS_KEY}}"
  local:
    configuration: {}
