metastore:
  client: glue
execution_engine:
  client: glue
scheduler:
  client: glue
  configuration:
    aws_role_arn: "arn:aws:iam::062325279035:role/service-role/AWSGlueServiceRole-anduin-data-glue"

