metastore_client: glue
scheduler_client: glue
storage_client: s3
clients:
  glue:
    configuration:
      region: "us-east-1"
      aws_role_arn: "arn:aws:iam::062325279035:role/service-role/AWSGlueServiceRole-anduin-data-glue"
  s3:
    configuration:
      region: "us-east-1"

