basePath: /api
consumes:
- application/json
info:
  description: Swagger UI for Mason Operator API
  title: Mason Operator API
  version: 1.0.0
produces:
- application/json
swagger: '2.0'
paths:
  /get:
    get:
      operationId: "mason.api.base.get"
      tags:
        - "Get"
      summary: "Get mason resource"
      description: "Get mason resource"
      consumes:
        - "application/json"
      parameters:
        - name: resource_type
          in: query
          required: true
          type: string
          enum:
            - all
            - operator
            - workflow
            - config
        - name: namespace
          in: query
          required: false
          type: string
        - name: command
          in: query
          required: false
          type: string
        - name: log_level
          in: query
          default: info
          enum:
            - info
            - warning
            - error
            - debug
            - trace
            - fatal
          required: false
          type: string
