paths:
  /table/{table_name}:
    get:
      operationId: "registered_operators.table.format.api"
      parameters:
        - name: database_name
          in: path
          type: string
          required: true
        - name: table_name
          in: query
          type: string
          required: true
        - name: format
          in: query
          type: string
          required: true
        - name: output_path
          in: query
          type: string
          required: true
          
        - name: partition_columns
          in: query
          type: string
          required: true
          
        - name: log_level
          in: query
          enum: [ "info", "warning", "error", "debug", "trace", "fatal"]
          required: false
          type: string
          default: "info"
          
      tags:
        - "Table"
      summary: "Format and repartition table and output to specified path"
      description: "Format and repartition table and output to specified path"
      responses:
        200:
          description: "Successful Format"

#  required:
#    - database_name
#    - table_name
#    - format
#    - output_path
#  optional:
#    - partition_columns
#    - filter_columns
#    - sample_size
#    - partitions
